[build-system]
requires = ["setuptools", "pip", "build", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'

[tool.pyright]
reportPrivateImportUsage = false
reportUnusedVariable = false
