name: main
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Clone Suitesparse
        run: git clone --depth 1 --branch v7.2.0 https://github.com/DrTimothyAldenDavis/SuiteSparse suitesparse

      - name: Clone Pybind
        run: |
          git clone --depth 1 --branch stable https://github.com/pybind/pybind11 pybind11

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  release:
    name: Create Release
    needs: [build_wheels]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Show dist contents
        run: ls dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
