name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Clone Suitsparse
        run: git clone --depth 1 --branch stable https://github.com/DrTimothyAldenDavis/SuiteSparse suitesparse
      - name: Clone Pybind
        run: |
          git clone --depth 1 --branch stable https://github.com/pybind/pybind11 pybind11

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          #CIBW_BEFORE_BUILD: pip install pybind11

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

