name: main
on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Suitesparse
        run: make suitesparse
      - name: Clone XLA
        run: make xla
      - name: Clone Pybind11
        run: make pybind11
      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_SKIP: "*-musllinux* pp*"
          CIBW_BEFORE_TEST: "pip install pytest"
          CIBW_TEST_COMMAND: "python {project}/.github/run_tests.py"
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          overwrite: true

  release:
    name: Create Release
    needs:
      - build-wheels
    runs-on: ubuntu-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Download Linux Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: dist
      - name: Download Windows Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist
      - name: Download MacOS Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: dist
      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
