name: pr
on:
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Clone Suitesparse
        run: make suitesparse

      - name: Clone XLA
        run: make xla

      - name: Clone Pybind11
        run: make pybind11

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD: 'cp312-macosx_universal2 cp312-win32 cp312-manylinux_x86_64'

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
